// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const allocateGameToStage = `-- name: AllocateGameToStage :one
insert into stage_games (stage_id, game_id)
values (?, ?)
returning id, stage_id, game_id, created_at, updated_at
`

type AllocateGameToStageParams struct {
	StageID sql.NullInt64
	GameID  sql.NullInt64
}

func (q *Queries) AllocateGameToStage(ctx context.Context, arg AllocateGameToStageParams) (StageGame, error) {
	row := q.db.QueryRowContext(ctx, allocateGameToStage, arg.StageID, arg.GameID)
	var i StageGame
	err := row.Scan(
		&i.ID,
		&i.StageID,
		&i.GameID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
insert into games (name,
                   team_a,
                   team_b,
                   results_log,
                   status,
                   rounds,
                   current_round)
values (?,
        ?,
        ?,
        ?,
        'pending',
        ?,
        ?)
returning id, name, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
`

type CreateGameParams struct {
	Name         string
	TeamA        sql.NullInt64
	TeamB        sql.NullInt64
	ResultsLog   json.RawMessage
	Rounds       json.RawMessage
	CurrentRound int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Name,
		arg.TeamA,
		arg.TeamB,
		arg.ResultsLog,
		arg.Rounds,
		arg.CurrentRound,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamA,
		&i.TeamB,
		&i.Winner,
		&i.Status,
		&i.Rounds,
		&i.CurrentRound,
		&i.ResultsLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStage = `-- name: CreateStage :one
insert into stages (name, status)
values (?, ?)
returning id, name, status, created_at, updated_at
`

type CreateStageParams struct {
	Name   string
	Status string
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, createStage, arg.Name, arg.Status)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTournament = `-- name: CreateTournament :one
insert into tournaments (name,
                         number_of_teams)
values (?,
        ?)
returning id, name, number_of_teams, created_at, updated_at
`

type CreateTournamentParams struct {
	Name          string
	NumberOfTeams int64
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, createTournament, arg.Name, arg.NumberOfTeams)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NumberOfTeams,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
select id, name, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
from games
where id = ?
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamA,
		&i.TeamB,
		&i.Winner,
		&i.Status,
		&i.Rounds,
		&i.CurrentRound,
		&i.ResultsLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompletedGamesByTeam = `-- name: ListCompletedGamesByTeam :many
select id, name, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
from games
where status = 'complete'
  and (team_a = ? or team_b = ?)
order by updated_at desc
`

type ListCompletedGamesByTeamParams struct {
	TeamA sql.NullInt64
	TeamB sql.NullInt64
}

func (q *Queries) ListCompletedGamesByTeam(ctx context.Context, arg ListCompletedGamesByTeamParams) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedGamesByTeam, arg.TeamA, arg.TeamB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamA,
			&i.TeamB,
			&i.Winner,
			&i.Status,
			&i.Rounds,
			&i.CurrentRound,
			&i.ResultsLog,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGame = `-- name: StartGame :exec
update games
set status = 'running'
where id = ?
`

func (q *Queries) StartGame(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startGame, id)
	return err
}

const updateGame = `-- name: UpdateGame :one
update games
set name          = ?,
    team_a        = ?,
    team_b        = ?,
    winner        = ?,
    status        = ?,
    results_log   = ?,
    rounds        = ?,
    current_round = ?
where id = ?
returning id, name, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
`

type UpdateGameParams struct {
	Name         string
	TeamA        sql.NullInt64
	TeamB        sql.NullInt64
	Winner       sql.NullInt64
	Status       string
	ResultsLog   json.RawMessage
	Rounds       json.RawMessage
	CurrentRound int64
	ID           int64
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.Name,
		arg.TeamA,
		arg.TeamB,
		arg.Winner,
		arg.Status,
		arg.ResultsLog,
		arg.Rounds,
		arg.CurrentRound,
		arg.ID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamA,
		&i.TeamB,
		&i.Winner,
		&i.Status,
		&i.Rounds,
		&i.CurrentRound,
		&i.ResultsLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStage = `-- name: UpdateStage :one
update stages
set name   = ?,
    status = ?
where id = ?
returning id, name, status, created_at, updated_at
`

type UpdateStageParams struct {
	Name   string
	Status string
	ID     int64
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, updateStage, arg.Name, arg.Status, arg.ID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
