// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createGame = `-- name: CreateGame :one
insert into games (name,
                   team_a,
                   team_b,
                   tournament_id,
                   results_log,
                   status,
                   rounds,
                   current_round)
values (?,
        ?,
        ?,
        ?,
        ?,
        'pending',
        ?,
        ?)
returning id, name, tournament_id, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
`

type CreateGameParams struct {
	Name         string
	TeamA        sql.NullInt64
	TeamB        sql.NullInt64
	TournamentID sql.NullInt64
	ResultsLog   json.RawMessage
	Rounds       json.RawMessage
	CurrentRound int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Name,
		arg.TeamA,
		arg.TeamB,
		arg.TournamentID,
		arg.ResultsLog,
		arg.Rounds,
		arg.CurrentRound,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.TeamA,
		&i.TeamB,
		&i.Winner,
		&i.Status,
		&i.Rounds,
		&i.CurrentRound,
		&i.ResultsLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
select id, name, tournament_id, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
from games
where id = ?
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.TeamA,
		&i.TeamB,
		&i.Winner,
		&i.Status,
		&i.Rounds,
		&i.CurrentRound,
		&i.ResultsLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
update games
set name          = ?,
    team_a        = ?,
    team_b        = ?,
    winner        = ?,
    status        = ?,
    results_log   = ?,
    rounds        = ?,
    current_round = ?,
    tournament_id = ?
where id = ?
returning id, name, tournament_id, team_a, team_b, winner, status, rounds, current_round, results_log, created_at, updated_at
`

type UpdateGameParams struct {
	Name         string
	TeamA        sql.NullInt64
	TeamB        sql.NullInt64
	Winner       sql.NullInt64
	Status       string
	ResultsLog   json.RawMessage
	Rounds       json.RawMessage
	CurrentRound int64
	TournamentID sql.NullInt64
	ID           int64
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.Name,
		arg.TeamA,
		arg.TeamB,
		arg.Winner,
		arg.Status,
		arg.ResultsLog,
		arg.Rounds,
		arg.CurrentRound,
		arg.TournamentID,
		arg.ID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.TeamA,
		&i.TeamB,
		&i.Winner,
		&i.Status,
		&i.Rounds,
		&i.CurrentRound,
		&i.ResultsLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
