// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Coach struct {
	ID        int64
	Name      string
	IsDefault sql.NullBool
	IsHuman   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Playbook struct {
	ID          int64
	Name        string
	TeamID      sql.NullInt64
	Description sql.NullString
	Formations  interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Player struct {
	ID        int64
	Name      string
	TeamID    sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Team struct {
	ID        int64
	Name      string
	IsDefault sql.NullBool
	CoachID   sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
