// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
)

type Coach struct {
	ID        int64
	Name      string
	IsDefault sql.NullBool
	IsHuman   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Game struct {
	ID           int64
	Name         string
	TournamentID sql.NullInt64
	TeamA        sql.NullInt64
	TeamB        sql.NullInt64
	Winner       sql.NullInt64
	Status       string
	Rounds       json.RawMessage
	CurrentRound int64
	ResultsLog   json.RawMessage
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Playbook struct {
	ID          int64
	Name        string
	TeamID      sql.NullInt64
	Description sql.NullString
	Formations  interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Player struct {
	ID        int64
	Name      string
	TeamID    sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Team struct {
	ID        int64
	Name      string
	IsDefault sql.NullBool
	CoachID   sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Tournament struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
