// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Coach struct {
	ID        interface{}
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Player struct {
	ID        interface{}
	Name      string
	TeamID    sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Team struct {
	ID        interface{}
	Name      string
	CoachID   sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
