// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playbook.sql

package database

import (
	"context"
	"database/sql"
)

const createPlaybook = `-- name: CreatePlaybook :one
insert into playbooks (name,
                       description,
                       formations,
                       team_id)
VALUES (?,
        ?,
        ?,
        ?)
RETURNING id, name, team_id, description, formations, created_at, updated_at
`

type CreatePlaybookParams struct {
	Name        string
	Description sql.NullString
	Formations  interface{}
	TeamID      sql.NullInt64
}

func (q *Queries) CreatePlaybook(ctx context.Context, arg CreatePlaybookParams) (Playbook, error) {
	row := q.db.QueryRowContext(ctx, createPlaybook,
		arg.Name,
		arg.Description,
		arg.Formations,
		arg.TeamID,
	)
	var i Playbook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamID,
		&i.Description,
		&i.Formations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaybook = `-- name: DeletePlaybook :exec
delete from playbooks where id = ?
`

func (q *Queries) DeletePlaybook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlaybook, id)
	return err
}

const getPlaybooksByTeam = `-- name: GetPlaybooksByTeam :many
select id, name, team_id, description, formations, created_at, updated_at from playbooks where team_id = ?
`

func (q *Queries) GetPlaybooksByTeam(ctx context.Context, teamID sql.NullInt64) ([]Playbook, error) {
	rows, err := q.db.QueryContext(ctx, getPlaybooksByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playbook
	for rows.Next() {
		var i Playbook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.Description,
			&i.Formations,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaybookFormations = `-- name: UpdatePlaybookFormations :one
update playbooks
set formations = ?
where id = ?
returning id, name, team_id, description, formations, created_at, updated_at
`

type UpdatePlaybookFormationsParams struct {
	Formations interface{}
	ID         int64
}

func (q *Queries) UpdatePlaybookFormations(ctx context.Context, arg UpdatePlaybookFormationsParams) (Playbook, error) {
	row := q.db.QueryRowContext(ctx, updatePlaybookFormations, arg.Formations, arg.ID)
	var i Playbook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamID,
		&i.Description,
		&i.Formations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
