// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package database

import (
	"context"
	"database/sql"
)

const getCoach = `-- name: GetCoach :one
SELECT id, name, coach_id FROM teams WHERE id = ?
`

func (q *Queries) GetCoach(ctx context.Context, id interface{}) (Team, error) {
	row := q.db.QueryRowContext(ctx, getCoach, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CoachID)
	return i, err
}

const getCoaches = `-- name: GetCoaches :many
SELECT id, name FROM coaches
`

func (q *Queries) GetCoaches(ctx context.Context) ([]Coach, error) {
	rows, err := q.db.QueryContext(ctx, getCoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coach
	for rows.Next() {
		var i Coach
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, coach_id FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id interface{}) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CoachID)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT id, name, team_id FROM players WHERE team_id = ?
`

func (q *Queries) GetTeamMembers(ctx context.Context, teamID sql.NullInt64) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Name, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeams = `-- name: GetTeams :many
SELECT id, name, coach_id FROM teams
`

func (q *Queries) GetTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.Name, &i.CoachID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
