// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package database

import (
	"context"
	"database/sql"
)

const clearDefaultCoach = `-- name: ClearDefaultCoach :exec
UPDATE coaches SET is_default = false WHERE is_default = true
`

func (q *Queries) ClearDefaultCoach(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultCoach)
	return err
}

const clearDefaultTeam = `-- name: ClearDefaultTeam :exec
UPDATE teams SET is_default = false WHERE is_default = true
`

func (q *Queries) ClearDefaultTeam(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultTeam)
	return err
}

const createCoach = `-- name: CreateCoach :one
INSERT INTO coaches (name, is_human, is_default) VALUES (?, ?, ?) RETURNING id, name, is_default, is_human, created_at, updated_at
`

type CreateCoachParams struct {
	Name      string
	IsHuman   sql.NullBool
	IsDefault sql.NullBool
}

func (q *Queries) CreateCoach(ctx context.Context, arg CreateCoachParams) (Coach, error) {
	row := q.db.QueryRowContext(ctx, createCoach, arg.Name, arg.IsHuman, arg.IsDefault)
	var i Coach
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsHuman,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, team_id) VALUES (?,?) RETURNING id, name, team_id, created_at, updated_at
`

type CreatePlayerParams struct {
	Name   string
	TeamID sql.NullInt64
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Name, arg.TeamID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, is_default, coach_id) VALUES (?, ?, ?) RETURNING id, name, is_default, coach_id, created_at, updated_at
`

type CreateTeamParams struct {
	Name      string
	IsDefault sql.NullBool
	CoachID   sql.NullInt64
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Name, arg.IsDefault, arg.CoachID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.CoachID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoach = `-- name: DeleteCoach :exec
DELETE FROM coaches WHERE id = ?
`

func (q *Queries) DeleteCoach(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoach, id)
	return err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE id = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getAICoaches = `-- name: GetAICoaches :many
SELECT id, name, is_default, is_human, created_at, updated_at FROM coaches WHERE is_human = false
`

func (q *Queries) GetAICoaches(ctx context.Context) ([]Coach, error) {
	rows, err := q.db.QueryContext(ctx, getAICoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coach
	for rows.Next() {
		var i Coach
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.IsHuman,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoach = `-- name: GetCoach :one
SELECT id, name, is_default, is_human, created_at, updated_at FROM coaches WHERE id = ?
`

func (q *Queries) GetCoach(ctx context.Context, id int64) (Coach, error) {
	row := q.db.QueryRowContext(ctx, getCoach, id)
	var i Coach
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsHuman,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoaches = `-- name: GetCoaches :many
SELECT id, name, is_default, is_human, created_at, updated_at FROM coaches
`

func (q *Queries) GetCoaches(ctx context.Context) ([]Coach, error) {
	rows, err := q.db.QueryContext(ctx, getCoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coach
	for rows.Next() {
		var i Coach
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.IsHuman,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultCoach = `-- name: GetDefaultCoach :one
SELECT id, name, is_default, is_human, created_at, updated_at FROM coaches WHERE is_default = true LIMIT 1
`

func (q *Queries) GetDefaultCoach(ctx context.Context) (Coach, error) {
	row := q.db.QueryRowContext(ctx, getDefaultCoach)
	var i Coach
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.IsHuman,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, is_default, coach_id, created_at, updated_at FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.CoachID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByCoachID = `-- name: GetTeamByCoachID :one
SELECT id, name, is_default, coach_id, created_at, updated_at FROM teams WHERE coach_id = ? LIMIT 1
`

func (q *Queries) GetTeamByCoachID(ctx context.Context, coachID sql.NullInt64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByCoachID, coachID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.CoachID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT id, name, team_id, created_at, updated_at FROM players WHERE team_id = ?
`

func (q *Queries) GetTeamMembers(ctx context.Context, teamID sql.NullInt64) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeams = `-- name: GetTeams :many
SELECT id, name, is_default, coach_id, created_at, updated_at FROM teams
`

func (q *Queries) GetTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.CoachID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultCoach = `-- name: SetDefaultCoach :exec
UPDATE coaches SET is_default = true WHERE id = ?
`

func (q *Queries) SetDefaultCoach(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultCoach, id)
	return err
}

const setDefaultTeam = `-- name: SetDefaultTeam :exec
UPDATE teams SET is_default = true WHERE id = ?
`

func (q *Queries) SetDefaultTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultTeam, id)
	return err
}

const updatePlayer = `-- name: UpdatePlayer :exec
UPDATE players SET name = ? WHERE id = ?
`

type UpdatePlayerParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayer, arg.Name, arg.ID)
	return err
}
