// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package database

import (
	"context"
	"database/sql"
)

const clearDefaultTeam = `-- name: ClearDefaultTeam :exec
UPDATE teams SET is_default = false WHERE is_default = true
`

func (q *Queries) ClearDefaultTeam(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultTeam)
	return err
}

const createCoach = `-- name: CreateCoach :exec
INSERT INTO coaches (name) VALUES (?) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCoach(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createCoach, name)
	return err
}

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (name, team_id) VALUES (?,?) RETURNING id, name, team_id, created_at, updated_at
`

type CreatePlayerParams struct {
	Name   string
	TeamID sql.NullInt64
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, createPlayer, arg.Name, arg.TeamID)
	return err
}

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (name, is_default, coach_id) VALUES (?, ?, ?) RETURNING id, name, is_default, coach_id, created_at, updated_at
`

type CreateTeamParams struct {
	Name      string
	IsDefault sql.NullBool
	CoachID   sql.NullInt64
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.ExecContext(ctx, createTeam, arg.Name, arg.IsDefault, arg.CoachID)
	return err
}

const deleteCoach = `-- name: DeleteCoach :exec
DELETE FROM coaches WHERE id = ?
`

func (q *Queries) DeleteCoach(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoach, id)
	return err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE id = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getCoach = `-- name: GetCoach :one
SELECT id, name, is_default, coach_id, created_at, updated_at FROM teams WHERE id = ?
`

func (q *Queries) GetCoach(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getCoach, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.CoachID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoaches = `-- name: GetCoaches :many
SELECT id, name, created_at, updated_at FROM coaches
`

func (q *Queries) GetCoaches(ctx context.Context) ([]Coach, error) {
	rows, err := q.db.QueryContext(ctx, getCoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coach
	for rows.Next() {
		var i Coach
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, is_default, coach_id, created_at, updated_at FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.CoachID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT id, name, team_id, created_at, updated_at FROM players WHERE team_id = ?
`

func (q *Queries) GetTeamMembers(ctx context.Context, teamID sql.NullInt64) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeams = `-- name: GetTeams :many
SELECT id, name, is_default, coach_id, created_at, updated_at FROM teams
`

func (q *Queries) GetTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.CoachID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultTeam = `-- name: SetDefaultTeam :exec
UPDATE teams SET is_default = false WHERE id = ?
`

func (q *Queries) SetDefaultTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultTeam, id)
	return err
}
