name: app ci

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.27.0'

      - name: Run generation
        run: task generate

      - name: Run format
        run: task format

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.12

      - name: Run sqlc vet
        run: sqlc vet

      - name: Run tests
        run: task cover
